services:
  # MongoDB para OrderAnalyze e CreditAnalysis
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    networks:
      - crediflow-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"

  # PostgreSQL para ClientCardCredit
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: client_credit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - crediflow-network
    ports:
      - "5432:5432"

  # Kafka para comunicação assíncrona
  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - crediflow-network
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data

  # Interface para visualizar os tópicos do Kafka
  redpanda-console:
    container_name: redpanda
    image: redpandadata/console:latest
    restart: on-failure
    ports:
      - "8081:8080"
    networks:
      - crediflow-network
    environment:
      KAFKA_BROKERS: "kafka:29092"  # Define o broker do Kafka
    depends_on:
      - kafka


  # Microsserviço OrderAnalyze
  order-analyze-service:
    build: './order-analyze-service'
    container_name: order-analyze-service
    depends_on:
      - mongo-db
      - kafka
    networks:
      - crediflow-network
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGO_DB_URI=mongodb://admin:123456@mongo-db:27017/crediflow
    ports:
      - "3001:3000"

  # Microsserviço CreditAnalysis
  credit-analysis-service:
    build: './credit-analysis-service'
    container_name: credit-analysis-service
    depends_on:
      - mongo-db
      - kafka
    networks:
      - crediflow-network
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGO_DB_URI=mongodb://admin:123456@mongo-db:27017/crediflow
    ports:
      - "3002:3000"

  # Microsserviço ClientCardCredit
  client-card-credit-service:
    build: './client-card-credit-service'
    container_name: client-card-credit-service
    depends_on:
      - postgres-db
      - kafka
    networks:
      - crediflow-network
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=client_credit_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "3003:3000"

networks:
  crediflow-network:
    driver: bridge
