server:
  port: 3001

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: credit-analysis-group
      auto-offset-reset: latest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring:
        json:
          add:
            type:
              headers: false

  data:
    mongodb:
      database: crediflow
      uri: ${MONGO_DB_URI:mongodb://admin:123456@localhost:27017}

logging:
  level:
    org:
      apache:
        kafka: OFF